{{- if .Values.enabled }}
{{- if .Values.worker }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    spaceone.service: {{ .Values.name }}
  name: {{ .Values.name }}-worker
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas_worker | default .Values.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      spaceone.service: {{ .Values.name }}-worker
  template:
    metadata:
      annotations:
        spaceone.deployment.tool: helm
        spaceone.database-flag: {{ print .Values.database | sha256sum }}
        spaceone.shared-flag: {{ print .Values.global.shared | sha256sum }}
        spaceone.application-flag: {{ print .Values.application_worker | sha256sum }}
      labels:
{{ include "spaceone.labels" . | indent 8 }}
        spaceone.service: {{ .Values.name }}-worker
    spec:
      terminationGracePeriodSeconds: {{ .Values.gracePeriod }}
      containers:
        - name: {{ .Values.name }}-worker
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.version }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ['spaceone', 'scheduler', 'spaceone.{{ regexReplaceAll "-" .Values.name "_" }}']
          volumeMounts:
            - name: default-conf
              mountPath: /opt/spaceone/{{ .Values.name }}/config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: timezone
              mountPath: /etc/localtime
            - name: log-volume
              mountPath: /var/log/spaceone
            - name: database-conf
              mountPath: /opt/spaceone/{{ .Values.name }}/config/database.yaml
              subPath: database.yaml
              readOnly: true
            - name: shared-conf
              mountPath: /opt/spaceone/{{ .Values.name }}/config/shared.yaml
              subPath: shared.yaml
              readOnly: true
            - name: application-conf
              mountPath: /opt/spaceone/{{ .Values.name }}/config/application.yaml
              subPath: application.yaml
              readOnly: true
          env:
            - name: SPACEONE_CONFIG_FILE
              value: /opt/spaceone/{{ .Values.name }}/config/config.yaml

{{- if .Values.sidecar }}
{{- toYaml .Values.sidecar | nindent 8 }}
{{- end }}

{{- if .Values.global.backend.sidecar }}
{{- toYaml .Values.global.backend.sidecar | nindent 8 }}
{{- end }}

      volumes:
        - name: default-conf 
          configMap:
            name: {{ .Values.name }}-conf
        - name: database-conf
          configMap:
            name: {{ .Values.name }}-database-conf
        - name: shared-conf
          configMap:
            name: shared-conf
        - name: application-conf
          configMap:
            name: {{ .Values.name }}-application-worker-conf

{{- if .Values.volumes }}
{{- toYaml .Values.volumes | nindent 8 }}
{{- end }}

{{- if .Values.global.backend.volumes }}
{{- toYaml .Values.global.backend.volumes | nindent 8 }}
{{- end }}

{{- end }}
{{- end }}
