{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
      {{- if not (eq $key "nil") }}
    {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    spaceone.service: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  selector:
    spaceone.service: {{ .Values.name }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
{{- end }}
